name: CI

on: [push, pull_request]

env:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build -t mkdocs-image .
        chmod +x ./mkdockerize.sh
        ./mkdockerize.sh mkdocs-project produce

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test the Docker image
      run: |
        docker images mkdocs-image
        ./mkdockerize.sh mkdocs-project serve
        sleep 10
        curl http://localhost:8000
